// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PresentationData struct {
	CinemaId             int64    `protobuf:"varint,2,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	MovieId              int64    `protobuf:"varint,3,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresentationData) Reset()         { *m = PresentationData{} }
func (m *PresentationData) String() string { return proto.CompactTextString(m) }
func (*PresentationData) ProtoMessage()    {}
func (*PresentationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PresentationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresentationData.Unmarshal(m, b)
}
func (m *PresentationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresentationData.Marshal(b, m, deterministic)
}
func (m *PresentationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresentationData.Merge(m, src)
}
func (m *PresentationData) XXX_Size() int {
	return xxx_messageInfo_PresentationData.Size(m)
}
func (m *PresentationData) XXX_DiscardUnknown() {
	xxx_messageInfo_PresentationData.DiscardUnknown(m)
}

var xxx_messageInfo_PresentationData proto.InternalMessageInfo

func (m *PresentationData) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

func (m *PresentationData) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type CreateRequest struct {
	Data                 *PresentationData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetData() *PresentationData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateResponse struct {
	CreatedId            int64    `protobuf:"varint,1,opt,name=createdId,proto3" json:"createdId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreatedId() int64 {
	if m != nil {
		return m.CreatedId
	}
	return 0
}

type FindForCinemaRequest struct {
	CinemaId             int64    `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindForCinemaRequest) Reset()         { *m = FindForCinemaRequest{} }
func (m *FindForCinemaRequest) String() string { return proto.CompactTextString(m) }
func (*FindForCinemaRequest) ProtoMessage()    {}
func (*FindForCinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *FindForCinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindForCinemaRequest.Unmarshal(m, b)
}
func (m *FindForCinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindForCinemaRequest.Marshal(b, m, deterministic)
}
func (m *FindForCinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindForCinemaRequest.Merge(m, src)
}
func (m *FindForCinemaRequest) XXX_Size() int {
	return xxx_messageInfo_FindForCinemaRequest.Size(m)
}
func (m *FindForCinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindForCinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindForCinemaRequest proto.InternalMessageInfo

func (m *FindForCinemaRequest) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type FindForCinemaResponse struct {
	Ids                  []int64             `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Dates                []*PresentationData `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindForCinemaResponse) Reset()         { *m = FindForCinemaResponse{} }
func (m *FindForCinemaResponse) String() string { return proto.CompactTextString(m) }
func (*FindForCinemaResponse) ProtoMessage()    {}
func (*FindForCinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *FindForCinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindForCinemaResponse.Unmarshal(m, b)
}
func (m *FindForCinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindForCinemaResponse.Marshal(b, m, deterministic)
}
func (m *FindForCinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindForCinemaResponse.Merge(m, src)
}
func (m *FindForCinemaResponse) XXX_Size() int {
	return xxx_messageInfo_FindForCinemaResponse.Size(m)
}
func (m *FindForCinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindForCinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindForCinemaResponse proto.InternalMessageInfo

func (m *FindForCinemaResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindForCinemaResponse) GetDates() []*PresentationData {
	if m != nil {
		return m.Dates
	}
	return nil
}

type FindForMovieRequest struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindForMovieRequest) Reset()         { *m = FindForMovieRequest{} }
func (m *FindForMovieRequest) String() string { return proto.CompactTextString(m) }
func (*FindForMovieRequest) ProtoMessage()    {}
func (*FindForMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *FindForMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindForMovieRequest.Unmarshal(m, b)
}
func (m *FindForMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindForMovieRequest.Marshal(b, m, deterministic)
}
func (m *FindForMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindForMovieRequest.Merge(m, src)
}
func (m *FindForMovieRequest) XXX_Size() int {
	return xxx_messageInfo_FindForMovieRequest.Size(m)
}
func (m *FindForMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindForMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindForMovieRequest proto.InternalMessageInfo

func (m *FindForMovieRequest) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type FindForMovieResponse struct {
	Ids                  []int64             `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Dates                []*PresentationData `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindForMovieResponse) Reset()         { *m = FindForMovieResponse{} }
func (m *FindForMovieResponse) String() string { return proto.CompactTextString(m) }
func (*FindForMovieResponse) ProtoMessage()    {}
func (*FindForMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *FindForMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindForMovieResponse.Unmarshal(m, b)
}
func (m *FindForMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindForMovieResponse.Marshal(b, m, deterministic)
}
func (m *FindForMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindForMovieResponse.Merge(m, src)
}
func (m *FindForMovieResponse) XXX_Size() int {
	return xxx_messageInfo_FindForMovieResponse.Size(m)
}
func (m *FindForMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindForMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindForMovieResponse proto.InternalMessageInfo

func (m *FindForMovieResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *FindForMovieResponse) GetDates() []*PresentationData {
	if m != nil {
		return m.Dates
	}
	return nil
}

type ReadRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadResponse struct {
	Data                 *PresentationData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetData() *PresentationData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReadAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

type ReadAllResponse struct {
	Ids                  []int64             `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Dates                []*PresentationData `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ReadAllResponse) GetDates() []*PresentationData {
	if m != nil {
		return m.Dates
	}
	return nil
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type DeleteForCinemasRequest struct {
	CinemaIds            []int64  `protobuf:"varint,1,rep,packed,name=cinemaIds,proto3" json:"cinemaIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteForCinemasRequest) Reset()         { *m = DeleteForCinemasRequest{} }
func (m *DeleteForCinemasRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteForCinemasRequest) ProtoMessage()    {}
func (*DeleteForCinemasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *DeleteForCinemasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForCinemasRequest.Unmarshal(m, b)
}
func (m *DeleteForCinemasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForCinemasRequest.Marshal(b, m, deterministic)
}
func (m *DeleteForCinemasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForCinemasRequest.Merge(m, src)
}
func (m *DeleteForCinemasRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteForCinemasRequest.Size(m)
}
func (m *DeleteForCinemasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForCinemasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForCinemasRequest proto.InternalMessageInfo

func (m *DeleteForCinemasRequest) GetCinemaIds() []int64 {
	if m != nil {
		return m.CinemaIds
	}
	return nil
}

type DeleteForCinemasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteForCinemasResponse) Reset()         { *m = DeleteForCinemasResponse{} }
func (m *DeleteForCinemasResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteForCinemasResponse) ProtoMessage()    {}
func (*DeleteForCinemasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *DeleteForCinemasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForCinemasResponse.Unmarshal(m, b)
}
func (m *DeleteForCinemasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForCinemasResponse.Marshal(b, m, deterministic)
}
func (m *DeleteForCinemasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForCinemasResponse.Merge(m, src)
}
func (m *DeleteForCinemasResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteForCinemasResponse.Size(m)
}
func (m *DeleteForCinemasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForCinemasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForCinemasResponse proto.InternalMessageInfo

type DeleteForMoviesRequest struct {
	MovieIds             []int64  `protobuf:"varint,1,rep,packed,name=movieIds,proto3" json:"movieIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteForMoviesRequest) Reset()         { *m = DeleteForMoviesRequest{} }
func (m *DeleteForMoviesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteForMoviesRequest) ProtoMessage()    {}
func (*DeleteForMoviesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *DeleteForMoviesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForMoviesRequest.Unmarshal(m, b)
}
func (m *DeleteForMoviesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForMoviesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteForMoviesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForMoviesRequest.Merge(m, src)
}
func (m *DeleteForMoviesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteForMoviesRequest.Size(m)
}
func (m *DeleteForMoviesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForMoviesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForMoviesRequest proto.InternalMessageInfo

func (m *DeleteForMoviesRequest) GetMovieIds() []int64 {
	if m != nil {
		return m.MovieIds
	}
	return nil
}

type DeleteForMoviesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteForMoviesResponse) Reset()         { *m = DeleteForMoviesResponse{} }
func (m *DeleteForMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteForMoviesResponse) ProtoMessage()    {}
func (*DeleteForMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *DeleteForMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForMoviesResponse.Unmarshal(m, b)
}
func (m *DeleteForMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForMoviesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteForMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForMoviesResponse.Merge(m, src)
}
func (m *DeleteForMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteForMoviesResponse.Size(m)
}
func (m *DeleteForMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForMoviesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PresentationData)(nil), "proto.PresentationData")
	proto.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
	proto.RegisterType((*FindForCinemaRequest)(nil), "proto.FindForCinemaRequest")
	proto.RegisterType((*FindForCinemaResponse)(nil), "proto.FindForCinemaResponse")
	proto.RegisterType((*FindForMovieRequest)(nil), "proto.FindForMovieRequest")
	proto.RegisterType((*FindForMovieResponse)(nil), "proto.FindForMovieResponse")
	proto.RegisterType((*ReadRequest)(nil), "proto.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "proto.ReadResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "proto.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "proto.ReadAllResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto.RegisterType((*DeleteForCinemasRequest)(nil), "proto.DeleteForCinemasRequest")
	proto.RegisterType((*DeleteForCinemasResponse)(nil), "proto.DeleteForCinemasResponse")
	proto.RegisterType((*DeleteForMoviesRequest)(nil), "proto.DeleteForMoviesRequest")
	proto.RegisterType((*DeleteForMoviesResponse)(nil), "proto.DeleteForMoviesResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdf, 0x6b, 0xdb, 0x30,
	0x10, 0xae, 0xe3, 0x34, 0xdd, 0xae, 0x49, 0x6a, 0xae, 0x4d, 0xeb, 0xa9, 0xbf, 0x82, 0x9e, 0x02,
	0x63, 0x19, 0xcb, 0x06, 0x81, 0x6d, 0x2f, 0xa3, 0xa5, 0x2c, 0xb0, 0xc1, 0x30, 0x8c, 0xed, 0x55,
	0x8b, 0xf4, 0x60, 0x48, 0xed, 0xce, 0xf2, 0xfa, 0x8f, 0xed, 0x1f, 0x1c, 0xb6, 0x7e, 0x44, 0x52,
	0xd3, 0x41, 0x21, 0x4f, 0xb6, 0xee, 0xee, 0xfb, 0xee, 0xd3, 0xdd, 0x27, 0x18, 0x48, 0x51, 0xdd,
	0xe7, 0x4b, 0x31, 0xbd, 0xab, 0xca, 0xba, 0xc4, 0xdd, 0xf6, 0x43, 0x3f, 0x43, 0xf2, 0xad, 0x12,
	0x52, 0x14, 0x35, 0xab, 0xf3, 0xb2, 0xb8, 0x66, 0x35, 0x43, 0x02, 0xcf, 0x96, 0x79, 0x21, 0x6e,
	0xd9, 0x82, 0xa7, 0x9d, 0x71, 0x34, 0x89, 0x33, 0x7b, 0xc6, 0x14, 0xf6, 0x6e, 0xcb, 0xfb, 0x5c,
	0x2c, 0x78, 0x1a, 0xb7, 0x29, 0x73, 0xa4, 0x1f, 0x61, 0x70, 0x55, 0x09, 0x56, 0x8b, 0x4c, 0xfc,
	0xfe, 0x23, 0x64, 0x8d, 0x2f, 0xa1, 0xcb, 0x59, 0xcd, 0xd2, 0x68, 0x1c, 0x4d, 0xf6, 0x67, 0x27,
	0xaa, 0xef, 0x34, 0xec, 0x96, 0xb5, 0x45, 0x74, 0x0a, 0x43, 0x83, 0x96, 0x77, 0x65, 0x21, 0x05,
	0x9e, 0xc1, 0xf3, 0x65, 0x1b, 0xe1, 0x0b, 0xde, 0x72, 0xc4, 0xd9, 0x3a, 0x40, 0x67, 0x70, 0x74,
	0x93, 0x17, 0xfc, 0xa6, 0xac, 0xae, 0x5a, 0x69, 0xa6, 0xa9, 0xab, 0x3d, 0xf2, 0xb5, 0xd3, 0x9f,
	0x30, 0x0a, 0x30, 0xba, 0x55, 0x02, 0x71, 0xce, 0x65, 0x1a, 0x8d, 0xe3, 0x49, 0x9c, 0x35, 0xbf,
	0xf8, 0x0a, 0x76, 0x39, 0xab, 0x85, 0x4c, 0x3b, 0xe3, 0xf8, 0x7f, 0xe2, 0x55, 0x15, 0x7d, 0x0d,
	0x87, 0x9a, 0xf9, 0x6b, 0x33, 0x0d, 0x23, 0xc6, 0x19, 0x56, 0xe4, 0x0f, 0xeb, 0x87, 0x95, 0xaf,
	0x01, 0xdb, 0x52, 0x72, 0x0e, 0xfb, 0x99, 0x60, 0xdc, 0x28, 0x18, 0x42, 0x27, 0x37, 0xcd, 0x3b,
	0x39, 0xa7, 0x1f, 0xa0, 0xaf, 0xd2, 0xba, 0xdf, 0x93, 0x76, 0x94, 0xc0, 0xb0, 0x01, 0x7f, 0x5a,
	0xad, 0x34, 0x3d, 0xcd, 0xe0, 0xc0, 0x46, 0xb6, 0x75, 0x83, 0x4b, 0x18, 0x5c, 0x8b, 0x95, 0x58,
	0xfb, 0x28, 0xbc, 0x43, 0x02, 0x43, 0x53, 0xa0, 0x7a, 0xd2, 0x39, 0x9c, 0xa8, 0x88, 0x5d, 0xad,
	0x34, 0xe0, 0xc6, 0x45, 0x7a, 0xff, 0x46, 0xd4, 0x3a, 0x40, 0x09, 0xa4, 0x0f, 0x81, 0x9a, 0xf4,
	0x1d, 0x1c, 0xdb, 0x5c, 0xbb, 0x24, 0xe9, 0x78, 0x4c, 0xef, 0xd1, 0x50, 0xda, 0x33, 0x7d, 0xe1,
	0x48, 0x31, 0x28, 0x45, 0x38, 0xfb, 0xdb, 0x85, 0xbe, 0x7b, 0x69, 0x9c, 0x43, 0x4f, 0x79, 0x1e,
	0x8f, 0xf4, 0x4c, 0xbc, 0x07, 0x44, 0x46, 0x41, 0x54, 0x0b, 0xdb, 0xc1, 0x2f, 0x30, 0xf0, 0x8c,
	0x8c, 0xa7, 0xba, 0x72, 0xd3, 0x93, 0x20, 0x67, 0x9b, 0x93, 0x96, 0x6d, 0x01, 0x7d, 0xd7, 0x8b,
	0x48, 0xfc, 0x7a, 0xd7, 0xd1, 0xe4, 0x74, 0x63, 0xce, 0x52, 0xbd, 0x81, 0x6e, 0xe3, 0x07, 0x44,
	0x5d, 0xe6, 0x58, 0x91, 0x1c, 0x7a, 0x31, 0x0b, 0x79, 0x0f, 0x7b, 0xda, 0x42, 0x38, 0x72, 0x2a,
	0xd6, 0x26, 0x23, 0xc7, 0x61, 0xd8, 0x62, 0xe7, 0xd0, 0x53, 0xc3, 0xb6, 0x03, 0xf4, 0x9c, 0x63,
	0x07, 0x18, 0xd8, 0x65, 0x07, 0xbf, 0x43, 0x12, 0xee, 0x1d, 0x2f, 0xbc, 0xe2, 0x07, 0x4e, 0x22,
	0x97, 0x8f, 0xe6, 0x2d, 0x6d, 0x06, 0x07, 0xc1, 0xf2, 0xf1, 0x3c, 0x44, 0x79, 0x56, 0x22, 0x17,
	0x8f, 0xa5, 0x0d, 0xe7, 0xaf, 0x5e, 0x5b, 0xf0, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x68, 0xc2, 0x57, 0xbf, 0x05, 0x00, 0x00,
}
