os: linux
language: go
stages:
  - build
  - test
  - lint
  - docs
jobs:
  include:
    - stage: build
      name: "Build"
      go:
        - 1.12.x
      install:
        - PROTOBUF_VERSION=3.7.1
        - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
        - pushd /home/travis
        - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
        - unzip ${PROTOC_FILENAME}
        - bin/protoc --version
        - popd
        - echo $PATH
      script:
        - GO111MODULE=on
        - chmod +x ./build.sh
        - ./build.sh
    - stage: test
      name: "Unit Tests"
      go:
        - 1.12.x
      script:
        - go test ./... -cover
    - stage: lint
      name: "Lint Code"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0
      script:
        - golangci-lint run --deadline 20m --enable-all --disable=goimports --disable=lll --disable=dupl --tests=false
    - stage: docs
      name: "Build Documentation"
      go:
        - 1.11.x
      script:
        - echo Hello
