os: linux
language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
go:
  - 1.12.x
install:
  - PROTOBUF_VERSION=3.7.1
  - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - pushd /home/travis
  - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
  - unzip ${PROTOC_FILENAME}
  - bin/protoc --version
  - popd
  - echo $PATH
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0
script:
  - env GO111MODULE=on
  - chmod +x ./build.sh
  - ./build.sh
  - go test ./... -cover
  - golangci-lint run --deadline 20m --enable-all --disable=goimports --disable=lll --disable=dupl --tests=false
