// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Seat struct {
	Row                  int64    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetRow() int64 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Seat) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ReservationData struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PresentationId       int64    `protobuf:"varint,2,opt,name=presentationId,proto3" json:"presentationId,omitempty"`
	Seats                []*Seat  `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationData) Reset()         { *m = ReservationData{} }
func (m *ReservationData) String() string { return proto.CompactTextString(m) }
func (*ReservationData) ProtoMessage()    {}
func (*ReservationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ReservationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationData.Unmarshal(m, b)
}
func (m *ReservationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationData.Marshal(b, m, deterministic)
}
func (m *ReservationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationData.Merge(m, src)
}
func (m *ReservationData) XXX_Size() int {
	return xxx_messageInfo_ReservationData.Size(m)
}
func (m *ReservationData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationData.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationData proto.InternalMessageInfo

func (m *ReservationData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReservationData) GetPresentationId() int64 {
	if m != nil {
		return m.PresentationId
	}
	return 0
}

func (m *ReservationData) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type ReservationRequest struct {
	Data                 *ReservationData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(m, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetData() *ReservationData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReservationResponse struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	CreatedId            int64    `protobuf:"varint,2,opt,name=createdId,proto3" json:"createdId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (m *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(m, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *ReservationResponse) GetCreatedId() int64 {
	if m != nil {
		return m.CreatedId
	}
	return 0
}

type AcceptReservationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptReservationRequest) Reset()         { *m = AcceptReservationRequest{} }
func (m *AcceptReservationRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptReservationRequest) ProtoMessage()    {}
func (*AcceptReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *AcceptReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptReservationRequest.Unmarshal(m, b)
}
func (m *AcceptReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptReservationRequest.Marshal(b, m, deterministic)
}
func (m *AcceptReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptReservationRequest.Merge(m, src)
}
func (m *AcceptReservationRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptReservationRequest.Size(m)
}
func (m *AcceptReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptReservationRequest proto.InternalMessageInfo

func (m *AcceptReservationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AcceptReservationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptReservationResponse) Reset()         { *m = AcceptReservationResponse{} }
func (m *AcceptReservationResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptReservationResponse) ProtoMessage()    {}
func (*AcceptReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *AcceptReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptReservationResponse.Unmarshal(m, b)
}
func (m *AcceptReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptReservationResponse.Marshal(b, m, deterministic)
}
func (m *AcceptReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptReservationResponse.Merge(m, src)
}
func (m *AcceptReservationResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptReservationResponse.Size(m)
}
func (m *AcceptReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptReservationResponse proto.InternalMessageInfo

type CancelReservationRequest struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReservationRequest) Reset()         { *m = CancelReservationRequest{} }
func (m *CancelReservationRequest) String() string { return proto.CompactTextString(m) }
func (*CancelReservationRequest) ProtoMessage()    {}
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CancelReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReservationRequest.Unmarshal(m, b)
}
func (m *CancelReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReservationRequest.Marshal(b, m, deterministic)
}
func (m *CancelReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReservationRequest.Merge(m, src)
}
func (m *CancelReservationRequest) XXX_Size() int {
	return xxx_messageInfo_CancelReservationRequest.Size(m)
}
func (m *CancelReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReservationRequest proto.InternalMessageInfo

func (m *CancelReservationRequest) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

type CancelReservationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReservationResponse) Reset()         { *m = CancelReservationResponse{} }
func (m *CancelReservationResponse) String() string { return proto.CompactTextString(m) }
func (*CancelReservationResponse) ProtoMessage()    {}
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *CancelReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReservationResponse.Unmarshal(m, b)
}
func (m *CancelReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReservationResponse.Marshal(b, m, deterministic)
}
func (m *CancelReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReservationResponse.Merge(m, src)
}
func (m *CancelReservationResponse) XXX_Size() int {
	return xxx_messageInfo_CancelReservationResponse.Size(m)
}
func (m *CancelReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReservationResponse proto.InternalMessageInfo

type ReadAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

type ReadAllResponse struct {
	Ids                  []int64            `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Dates                []*ReservationData `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ReadAllResponse) GetDates() []*ReservationData {
	if m != nil {
		return m.Dates
	}
	return nil
}

func init() {
	proto.RegisterType((*Seat)(nil), "proto.Seat")
	proto.RegisterType((*ReservationData)(nil), "proto.ReservationData")
	proto.RegisterType((*ReservationRequest)(nil), "proto.ReservationRequest")
	proto.RegisterType((*ReservationResponse)(nil), "proto.ReservationResponse")
	proto.RegisterType((*AcceptReservationRequest)(nil), "proto.AcceptReservationRequest")
	proto.RegisterType((*AcceptReservationResponse)(nil), "proto.AcceptReservationResponse")
	proto.RegisterType((*CancelReservationRequest)(nil), "proto.CancelReservationRequest")
	proto.RegisterType((*CancelReservationResponse)(nil), "proto.CancelReservationResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "proto.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "proto.ReadAllResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xe2, 0x30,
	0x10, 0xc5, 0x21, 0x01, 0x76, 0x77, 0x22, 0x58, 0xd6, 0xab, 0x45, 0x21, 0xbb, 0xd2, 0x66, 0xad,
	0x55, 0x85, 0x50, 0x85, 0x2a, 0x7a, 0xeb, 0x09, 0xda, 0x5e, 0x38, 0xf4, 0x40, 0x7a, 0xe9, 0xd5,
	0xc4, 0x73, 0x88, 0x94, 0x26, 0xa9, 0x6d, 0xe8, 0x37, 0xeb, 0xe7, 0xab, 0xec, 0x98, 0xf0, 0x2f,
	0x39, 0x81, 0xdf, 0xcc, 0xfc, 0xfc, 0xfc, 0x26, 0xd0, 0x97, 0x28, 0x76, 0x49, 0x8c, 0xb3, 0x42,
	0xe4, 0x2a, 0x27, 0x5d, 0xf3, 0x43, 0x6f, 0xa0, 0xf3, 0x8c, 0x4c, 0x91, 0x21, 0xb8, 0x22, 0x7f,
	0xf7, 0xdb, 0x61, 0x7b, 0xe2, 0x46, 0xfa, 0x2f, 0x19, 0x41, 0x2f, 0xdb, 0xbe, 0x6e, 0x50, 0xf8,
	0x8e, 0x11, 0xed, 0x89, 0x2a, 0xf8, 0x1e, 0xa1, 0x66, 0x31, 0x95, 0xe4, 0xd9, 0x23, 0x53, 0x4c,
	0xb7, 0x6e, 0x25, 0x8a, 0x15, 0xb7, 0xf3, 0xf6, 0x44, 0xae, 0x60, 0x50, 0x08, 0x94, 0x98, 0x29,
	0xd3, 0xbb, 0xe2, 0x16, 0x75, 0xa6, 0x92, 0x7f, 0xd0, 0x95, 0xc8, 0x94, 0xf4, 0xdd, 0xd0, 0x9d,
	0x78, 0x73, 0xaf, 0xb4, 0x38, 0xd3, 0xc6, 0xa2, 0xb2, 0x42, 0x17, 0x40, 0x8e, 0x6e, 0x8d, 0xf0,
	0x6d, 0x8b, 0x52, 0x91, 0x29, 0x74, 0x38, 0x53, 0xcc, 0x5c, 0xeb, 0xcd, 0x47, 0x76, 0xee, 0xcc,
	0x5e, 0x64, 0x7a, 0xe8, 0x1a, 0x7e, 0x9e, 0x10, 0x64, 0x91, 0x67, 0x12, 0xc9, 0x1f, 0xf8, 0xc6,
	0x76, 0x2c, 0x49, 0xd9, 0x26, 0x45, 0xc3, 0xf9, 0x1a, 0x1d, 0x04, 0x5d, 0x8d, 0x05, 0x32, 0x85,
	0xbc, 0x32, 0x7f, 0x10, 0xe8, 0x14, 0xfc, 0x65, 0x1c, 0x63, 0xa1, 0x6a, 0xac, 0x0d, 0xc0, 0x49,
	0xf6, 0x79, 0x38, 0x09, 0xa7, 0xbf, 0x61, 0x5c, 0xd3, 0x5b, 0x9a, 0xa0, 0x0b, 0xf0, 0x1f, 0x58,
	0x16, 0x63, 0x5a, 0x03, 0xfa, 0x0f, 0x7d, 0x71, 0x50, 0xab, 0x8c, 0x4f, 0x45, 0x8d, 0xaf, 0x21,
	0x58, 0xfc, 0x10, 0x06, 0x11, 0x32, 0xbe, 0x4c, 0x53, 0x0b, 0xa5, 0x6b, 0xbd, 0x44, 0xab, 0xd8,
	0x20, 0x86, 0xe0, 0x26, 0x5c, 0xfa, 0xed, 0xd0, 0xd5, 0x5f, 0x40, 0xc2, 0x25, 0xb9, 0x86, 0x2e,
	0x67, 0x0a, 0xa5, 0xef, 0x98, 0xb5, 0x34, 0xc5, 0x5b, 0x36, 0xcd, 0x3f, 0x1c, 0xf0, 0x8e, 0x4a,
	0xe4, 0x1e, 0xbe, 0x94, 0x47, 0x24, 0xe3, 0xcb, 0x49, 0x6b, 0x24, 0x08, 0xea, 0x4a, 0xd6, 0x76,
	0x8b, 0xbc, 0xc0, 0x8f, 0x8b, 0xd0, 0xc8, 0x5f, 0x3b, 0xd2, 0x14, 0x7d, 0x10, 0x36, 0x37, 0x54,
	0xe4, 0x27, 0xe8, 0x95, 0x79, 0x55, 0xb8, 0xa6, 0x05, 0x54, 0xb8, 0xe6, 0x7c, 0x5b, 0xe4, 0x4e,
	0x3f, 0xd6, 0xe4, 0x49, 0x7e, 0x55, 0x2f, 0x3a, 0x4e, 0x3c, 0x18, 0x9d, 0xcb, 0xfb, 0xd9, 0x4d,
	0xcf, 0x14, 0x6e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x48, 0x58, 0x9d, 0x6c, 0xa1, 0x03, 0x00,
	0x00,
}
